---
title: "Saint Survey"
output: html_notebook
---

```{r}
# Load the libraries
library(dplyr)
library(ggplot2)
library(lubridate)
library(factoextra)
library(car)
nreligion<-read.csv("encuesta.csv", header=TRUE)
```

```{r}
nrcat<- nreligion[nreligion$RELIGION=="Católica",]
View(nrcat)
```

```{r}
nrtest<- nreligion[nreligion$RELIGION=="Testigos de Jehova",]
View(nrtest)
```

```{r}
nragno<-nreligion[nreligion$RELIGION=="Agnóstico/a",]
View(nragno)
```

```{r}
nrpent<-nreligion[nreligion$RELIGION=="Pentecostes",]
View(nrpent)
```

```{r}
nrluz<-nreligion[nreligion$RELIGION=="Luz del mundo",]
View(nrluz)
```

```{r}
nrnin<-nreligion[nreligion$RELIGION=="Ninguna",]
View(nrnin)
```

```{r}
nrcatH<-nrcat[nrcat$SEXO=="Masculino",]
View(nrcatH)
summary(nrcatH)
```

```{r}
nrcatM<-nrcat[nrcat$SEXO=="Femenino",]
#View(nrcatM)
summary(nrcatM)
```

```{r}
nrcatMSinS<-nrcatM[nrcatM$SANTO=="",]
View(nrcatMSinS)
nrcatHSinS<-nrcatH[nrcatH$SANTO=="",]
View(nrcatHSinS)
```

```{r}
hist(nrcatM$EDAD)
hist(nrcatH$EDAD)
```

```{r}
nrcgen<-nreligion[nreligion$RELIGION=="Católica",]
summary(nrcgen)
```

```{r}
nrcatMConS<-nrcatM[nrcatM$SANTO,]
View(nrcatMConS)
```


```{r}
#str(nreligion)
str(dcovid)
```

```{r}
nrdios<-nreligion[nreligion$CREENCIA=="Dios (deidad única);",]
#View(nrdios)
boxplot(nrdios$EDAD)
nrsantos<-nreligion[nreligion$CREENCIA=="Santos",]
View(nrsantos)
boxplot(nrsantos$EDAD)
```
```{r}
hist(nrcat$EDAD)
boxplot(nrcat$EDAD)
```

```{r}
shapiro.test(nrcat$EDAD)
```
```{r}
leveneTest(y=nreligion$EDAD, group = nreligion$RELIGION=="Católica", center = "min")
```

```{r}
summary(nrcat$EDAD)
```


